Fix more lintian issues
* Remove leading article in omfdef description
* Use init-functions in oml2-server init script

refs: #1717

Signed-off-by: Olivier Mehani <olivier.mehani@nicta.com.au>

diff --git a/debian/oml2-server.init b/debian/oml2-server.init
--- a/debian/oml2-server.init
+++ b/debian/oml2-server.init
@@ -17,25 +17,37 @@
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="OML2 Measurements Collection Server"
 NAME=oml2-server
+DAEMON=/usr/bin/$NAME
 PIDFILE=/var/run/$NAME.pid
 FIN_WAIT_TO=`cat /proc/sys/net/ipv4/tcp_fin_timeout`
 
-test -x /usr/bin/$NAME || exit 0
+test -x $DAEMON || exit 0
+
+umask 022
 
 if [ -f /etc/default/oml2-server ]; then
     . /etc/default/oml2-server
 fi
 
+. /lib/lsb/init-functions
+
 start(){
-    echo -n "Starting OML server: $NAME"
-	start-stop-daemon --start --quiet --background --pidfile $PIDFILE --make-pidfile --exec /usr/bin/$NAME -- $OPTS
-    echo "."
+    log_daemon_msg "Starting OML server: $NAME" || true
+    if start-stop-daemon --start --quiet --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $OPTS; then
+	log_end_msg 0 || true
+    else
+	log_end_msg 1 || true
+    fi
+
 }
 
 stop(){
-    echo -n "Stopping OML server: $NAME"
-	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
-    echo "."
+    log_daemon_msg "Stopping OML server: $NAME" || true
+    if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
+	log_end_msg 0 || true
+    else
+	log_end_msg 1 || true
+    fi
 }
 
 
@@ -61,35 +73,47 @@ wait_stop(){
 	# Wait for the process to terminate
 	while kill -0 "${PID:-}" 2> /dev/null;  do
 	    if [ $i = '60' ]; then
+		FAILED=yes
 		break;
 	    else
 		if [ $i = '0' ]; then
-		    echo -n "waiting"
+		    log_progress_msg "Waiting for $NAME to terminate" || true
 		else
-		    echo -n "."
+		    log_progress_msg "." || true
 		fi
 		i=$(($i+1))
 		sleep 1
 	    fi
 	done
+	if [ x$FAILED != xyes ]; then
+	    log_end_msg 0 || true
+	else
+	    log_progress_msg "(failed to stop)" || true
+	    log_end_msg 1 || true
+	fi
     fi
     # Wait for the kernel to have cleaned up FIN_WAIT sockets (#1262)
+    log_progress_msg "Waiting for ${FIN_WAIT_TO}s (FIN_WAIT)" || true
     sleep ${FIN_WAIT_TO}
+    log_end_msg 0 || true
 }
 
 case "$1" in
-  start)
-    start
-    ;;
-  stop)
-    stop
-    ;;
-  restart|force-reload)
-    wait_stop
-    start
-    ;;
-  *)
-	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}"
+    start)
+	start
+	;;
+    stop)
+	stop
+	;;
+    restart|force-reload)
+	wait_stop
+	start
+	;;
+    status)
+	status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
+	;;
+    *)
+	log_action_msg "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" || true
 	exit 1
 esac
 
